name: build and deploy

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose-plugin

      - name: Build and run containers
        run: |
          docker compose up -d --build

      - name: Wait for services to be ready
        run: |
          while ! docker compose exec -T db pg_isready; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Run tests
        run: |
          docker compose exec -T app sh -c "python manage.py test"

      - name: Stop and remove containers
        if: always()
        run: |
          docker compose down
